services:
  service-pg:
    container_name: service-postgresql
    image: bitnami/postgresql
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=church_api